### ISSUE TITLE
How does directory structure detection works (if it works)

### ISSUE THREAD

**Issue by gacekssj4** [Dingmatt/AMSA#21]
Hello, I do not know if its bug or my misconfiguration. I did all according to settings.

I created folder according to README.md and it looks as follows
```
[Judas] Golden Kamuy/S01/[episodes]
[Judas] Golden Kamuy/S02/[episodes]
[Judas] Golden Kamuy/S03/[episodes]
```
This series is being displayed in main view, but as "Collection" (under it there is `1 Series`).

On the other hand I have 
```
[Judas] Beastars/S01/[episodes]
[Judas] Beastars/S02/[episodes]
[Judas] Beastars/S03/[episodes]
```
And in main view Beastars display as "Serie" (under it it says there are 2 seasons).

Why is it being detected differently?

**Comment by gacekssj4** [comment]
Sorry to bother you @Dingmatt Could you help? :)

**Comment by Dingmatt** [comment]
AMSA is set up to use the Plex file naming structure, so while some deviation is usually fine, it's best to stick to the default asides from special cases like OP's and ED's (opening and endings).

So to quote the readme, your structure should follow:

     /Golden Kamuy
        /Season 1
           Golden Kamuy - S01E01 - [Episode Name]
           Golden Kamuy - S01E02 - [Episode Name]
           Golden Kamuy - S01E03 - [Episode Name]
           
Using 'S01' rather than 'Season 1' shouldn't be a problem though using the release group as a tag will likely cause problems.

Regards,
