### ISSUE TITLE
TVDB

### ISSUE THREAD

**Issue by daomengRen** [Dingmatt/AMSA#26]
Hello, is TVDB obtained through API? Does TVDB still support the free API applied for? Thank you

**Comment by Dingmatt** [comment]
The TVDB info is obtained through their api via a legacy key, this key is still active but TVDB will be revoking it at some point in 2021, at that point users will have to subscribe to TVDB via a personal licence which they'll be able to enter into the AMSA settings.

I'll be keeping my eyes open for other metadata sources to add to the plugin in order to compensate, though AniDB will be able to pick up much of the slack.
