### ISSUE TITLE
Matching well, without metadata and posters

### ISSUE THREAD

**Issue by kikoptr** [Dingmatt/AMSA#40]
I'm sorry to reopen this ticket #39 but I have the same problem and I can't solve it.
I have checked the Cache files and in my case these are generated, one of them without XML extension so I do not know if it is a bug or a change in the latest version:
```
anime-list-corrections.xml
anime-list-master.xml
anime-movieset-list.xml
anime-titles
```
Other than that, in the Plex log when I'm trying to download metadata or apply an ID correction I've gotten this a couple of times:
```
tvdb:71: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
The '--scan' operation is deprecated and will be removed in future versions of Plex Media Server.
```
Once I have identified the series, the titles remain with the "anidb" and no posters or descriptions are downloaded. What can I do to fix this?

Thanks.

**Comment by Dingmatt** [comment]
Each time this issue has arisen it's due to one of two issues, either its permissions or a soft aniDB ban; though it could also be both.

Try visiting the [the following link](http://api.anidb.net:9001/httpapi?request=anime&client=amsa&clientver=1&protover=1&aid=14107), if you see a 'denied' or 'forbidden' looking message then it'll be a soft ban, you'll have to wait around 24 hours before AMSA will be able to continue its data collection (after which you can use the 'Refresh All Metadata' option).

If you click that link and see data then it'll be a permissions issue, you'll need to grant the plex user access to the AMSA folders. If you're using Linux or a NAS then the [following guide](https://support.plex.tv/articles/200288596-linux-permissions-guide/) might help.

Regards

**Comment by Dingmatt** [comment]
Sorry for the late reply.

AMSA will currently fail to gather data if one of the sources specified isn't available (in general, rather than simply a particular show); at the moment that behaviour is as designed, as it highlights an issue with the source, rather than going undetected.

As for the spanish language, it'll only be able to gather the metadata if available at the source. I'd recommend swapping your priorities to 'TVDB,AniDB,Plex' as TVDB actually has a better range of languages available for most shows.
