### ISSUE TITLE
Movie Detection

### ISSUE THREAD

**Issue by Mcsaxo1990** [Dingmatt/AMSA#47]
Hello and thanks for your work.

I have some problem with my libary

**Example:**
\Movie
   I Like the Sample Movie (2023).mkv
\Specials
  NAME OVA 01
\Extra
  NAME Creditless OP 1
  NAME Creditless OP 1
\[Season 01] NAME
\[Season 02] NAME
\[Season 03] NAME

My Problem is first i cannot detect the movie and i dont want a extra Libary any idears to solve this problem?
The Second is that i canot display the extra stuff... to be hornest i have trouble to put in bigger series the ova korrekt but thats a other thing :D

Greetings

**Comment by Dingmatt** [comment]
Hi Mcsaxo, AMSA isn't designed to detect moves unless they're a known special within a series; this is by design. If you require movie detection then I'd recommend [Hama](https://github.com/ZeroQI/Hama.bundle).

As for the extras, you need to follow the folder / naming convention specified in the readme in order for them to be detected.
