### ISSUE TITLE
Could you please support other languages?

### ISSUE THREAD

**Issue by cokebar** [Dingmatt/AMSA#7]
For now it only support English

**Comment by Dingmatt** [comment]
Hi,

The agent currently supports multilingual series and episode naming which can be selected from the setting menu.

![image](https://user-images.githubusercontent.com/14905596/29751445-540a61b8-8b45-11e7-9025-3dab534efe6e.png)

As for other meta information such as description, genre, etc its limited to the sources currently used, TVDB and AniDB are predominantly English sites so don't store much of the metadata in other languages; I'd need to find a multilingual metadata source (or multiple) in order to offer that functionality. I'm happy to do that but only one the agents beyond its beta and the existing agents are feature complete.

The agent itself is currently limited to English (settings menu, documentation, etc) though again I'd be happy to expand that once I have the time, though the fist iterations may need to be google translated with community driven corrections going forward.

Regards,

**Comment by eversins** [comment]
If you could change the language on the library selection it would be great too, that way if it searches on TheTVDB etc it would get localized titles.
