### ISSUE TITLE
Nice but.. 

### ISSUE THREAD

**Issue by Pahiro** [Dingmatt/AMSA#8]
Only problem I have so far is any text after the title means I don't get a match. This includes the year sometimes. Doing manual matching for most of the stuff. And for the 1995 Ghost in the shell movie, even though I select the correct match from anidb manually, it keeps pulling the series data ie. Stand Alone Complex.

**Comment by Dingmatt** [comment]
Hi @Pahiro. 
Firstly can you tell me which version of the agent are you using? If its the latest demo then the search is title specific so adding additional details (such as the year) won't bring up additional matches, you can specify year within the 'search options'.

Also the agent doesn't currently cater for movies unless they're listed as one of the specials for a given series, the reason its matching Stand Alone Complex is because the movie is listed in TVDB as its S00E01 special; I'm planning on adding stand alone movies in the future but I'll be finishing off the existing features before adding any new.

I'll need a bit for information to check if this is a bug or missing feature, are you using the included ASS (scanner) for your library and can I get a sample of your library structure (folder and filenames, typed or screenshot is fine)?

**Comment by Pahiro** [comment]
Using the latest demo/test version. Don't have a renamer for the downloads, which is causing the trouble. Doing a manual search does bring up the correct matches (after I remove the bad data) and stores them under specials as stated above. Also using the AS scanner. Folder structure is pretty simple at the moment. It's literally just as I get it from SABNzbd. Created an anime profile which moves it into /anime/<series_name>/season<number>/ (Original folder structure from download) and /anime/<movie_title>.

With the above example it looks as follows; /anime/Ghost.in.the.Shell.1995.720p.Bluray.x265-x0r/Ghost.in.the.Shell.1995.720p.Bluray.x265-x0r.mp4

With a manual search I get [anidb-61], which I click on to try and force the correct metadata but it always goes back to Stand Alone Complex, no matter what I do.

**Comment by Dingmatt** [comment]
Thanks for the details, that enough to go on. You're right about the filename and folder structure, your current setup will definitely hinder the agents ability to auto-match; with that in mind it might be worth trying the latest ASS version ([found here](https://github.com/ZeroQI/Absolute-Series-Scanner)) as its constantly improving and might make things easier for you.

As for the Ghost in the Shell Movie. I'm afraid that's a perfect example of a stand alone movie which isn't supported by the agent yet, the agent literally ignores any AniDB movie data at the moment; I will add support for them eventually but it won't be for a while. 

If you're looking for an agent that supports both anime movie and series data then I'd recommend [ZeroQi's Hama Agent](https://github.com/ZeroQI/Hama.bundle) though it uses the same scanner as AMSA so you many have the same matching issues.

**Comment by Pahiro** [comment]
Hama for some reason didn't want to bring through the posters. I'll double check chown for the data folders again and give it another shot. I'll keep an eye on yours as well though.

**Comment by Dingmatt** [comment]
Good luck, it might be worth trying the Hama Beta as its got less setup issues.
